### ISSUE TITLE
Support for mobile app

### ISSUE THREAD

**Issue by mwoz123** [gokulk16/select-current-line-plugin#1]
Hello first of all many thanks for your plugin and your work :)

Is there a chance to extended it so that select current line action is visible in command palette? 

This way it can support mobile devices as it could be used as an editor's button (from command palette actions) or used in even more complicated macro. 

Thanks 
Marcin

**Comment by mwoz123** [comment]
Actually I've just checked and it work on mobile :trophy: 

Just required to set in [mainifest.json](https://github.com/gokulk16/select-current-line-plugin/blob/74301e60ed30ded5b6261463a7721449593fbca6/manifest.json#LL10C2-L10C2) the line 
`isDesktopOnly` to `false` and it can be used on mobile e.g. in [commander](https://github.com/phibr0/obsidian-commander) macros :) 

Could you adopt it ? Thanks :)

**Comment by mfp22** [comment]
I see a change was made, but I just installed this plugin and it's not enabling on Android. Does it still need to be updated in the Obsidian store? For now I'll try to edit the source code directly

**Comment by mfp22** [comment]
This would add this to the icon commands available in the mobile editor button. Add to command definition:
```
      mobileOnly: true,
      iconName: '',
```

I think mobile only just means it gets added as a mobile command. It shouldn't exclude desktop

I think these are the icon names to choose from https://forum.obsidian.md/t/list-of-available-icons-for-component-seticon/16332/4

**Comment by mwoz123** [comment]
Yes, it needs to published by @gokulk16 as new version to obsidian store to make it work for everyone.

**Comment by mwoz123** [comment]
> This would add this to the icon commands available in the mobile editor button. Add to command definition:
> 
> ```
>       mobileOnly: true,
>       iconName: '',
> ```
> 
> I think mobile only just means it gets added as a mobile command. It shouldn't exclude desktop
> 
> I think these are the icon names to choose from https://forum.obsidian.md/t/list-of-available-icons-for-component-seticon/16332/4

Could you also make it available on Desktop? I'm also using on desktop (as commander macro) to select a line under cursor and extract it to new file.

**Comment by mwoz123** [comment]
I'm afraid that that `mobileOnly: true` means that it will be excluded from desktop

**Comment by gokulk16** [comment]
@mwoz123 @mfp22 Thanks for the ask 🙏 .
I have fixed this by changing the manifest.json file. You can re-install the plugins and things should work.
I have also tested it on my mobile.

**Comment by gokulk16** [comment]
@mfp22 I don't think any icon would do justice for selecting a line from this [list]( https://forum.obsidian.md/t/list-of-available-icons-for-component-seticon/16332/4). 
But still, the plugin command can be added to icon commands immobile app. The icon will be just a question mark symbol.
Let know if anything.

**Comment by gokulk16** [comment]
Closing the issue since this is fixed.

**Comment by mwoz123** [comment]
Great:) mamy thanks @gokulk16 

Ps: how about add to read me info that it can be used on mobile form command palette or used in macros? ;)
